### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by cscashby** [pimoroni/inky#57] opened 2020-08-11 11:57 UTC
Two (yellow) Inky Phats, multiple Pi variants (Pi Zero W 1.1, Pi 3B+, Pi 4B)

Main thread here:
https://forums.pimoroni.com/t/inkyphat-not-working/14667/14

Mounting pics here: https://photos.app.goo.gl/RagyP2RHYzHoe6Mw6

If someone can give me some debug help - something like i2cdetect but for SPI, or a way of directly interrogating the board would be handy so I can see what might be wrong here.

Possibly buster specific challenge, not tried with older OS versions.

**Comment by cscashby** [comment] 2020-08-12 12:12
More info on this. I've done a clean stretch install on a Pi Zero W 1.1 (hoping it was a buster specific issue, but no joy).

`apt update`
`apt full-upgrade`

`raspi-config` - enable SPI

Then install:

Complete output attached:
```
pi@raspberrypi:~ $ curl https://get.pimoroni.com/inky | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38853  100 38853    0     0   102k      0 --:--:-- --:--:-- --:--:--  103k

This script will install everything needed to use
Inky pHAT & wHAT

Always be careful when running scripts and commands copied
from the internet. Ensure they are from a trusted source.

If you want to see what this script does before running it,
you should run: 'curl https://get.pimoroni.com/inky'

Note: Inky pHAT & wHAT requires SPI communication

Do you wish to continue? [y/N] y

Checking environment...
Updating apt indexes...
...............
...
Checking hardware requirements...

Checking for packages required for GPIO control...
...raspi-gpio is already installed
.....................RPi.GPIO installed and up-to-date

SPI already enabled

Checking packages required by SPI interface...
spidev installed and up-to-date

Inky pHAT & wHAT comes with examples and documentation that you may wish to install.
Performing a full install will ensure those resources are installed,
along with all required dependencies. It may however take a while!

Do you wish to perform a full install? [y/N] y

Checking for dependencies...
python-numpy is already installed
python3-numpy is already installed
python-pil is already installed
python3-pil is already installed
python-lxml is required
Installing python-lxml...
python3-lxml is required
Installing python3-lxml...
python-smbus is already installed
python3-smbus is already installed

Installing Inky pHAT & wHAT library for Python 2...

Collecting inky
  Downloading https://files.pythonhosted.org/packages/88/b9/562fdebbbc0cb6f4781687dd9be31161efb7048b2127c5ec22d847747362/inky-0.0.5-py2-none-any.whl
Collecting smbus2 (from inky)
  Downloading https://www.piwheels.org/simple/smbus2/smbus2-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib/python2.7/dist-packages (from inky)
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from inky)
Requirement already satisfied: spidev in /usr/lib/python2.7/dist-packages (from inky)
Installing collected packages: smbus2, inky
Successfully installed inky-0.0.5 smbus2-0.3.0

Installing Inky pHAT & wHAT library for Python 3...

Collecting inky
  Downloading https://files.pythonhosted.org/packages/b8/29/0ce8c4bd259a5ac4e4657686d357ba7c45810adfcf6011ae84ac730bd1ad/inky-0.0.5-py3-none-any.whl
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from inky)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from inky)
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from inky)
Collecting smbus2 (from inky)
  Using cached https://www.piwheels.org/simple/smbus2/smbus2-0.3.0-py2.py3-none-any.whl
Installing collected packages: smbus2, inky
Successfully installed inky-0.0.5 smbus2-0.3.0

Checking for additional software...
python-geocoder is required
Installing python-geocoder...
E: Unable to locate package python-geocoder
Apt failed to install python-geocoder!
Falling back on pypi...
Collecting geocoder
  Downloading https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl (98kB)
    100% |████████████████████████████████| 102kB 338kB/s 
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from geocoder)
Collecting future (from geocoder)
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 88kB/s 
Requirement already satisfied: click in /usr/lib/python2.7/dist-packages (from geocoder)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from geocoder)
Collecting ratelim (from geocoder)
  Downloading https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl
Collecting decorator (from ratelim->geocoder)
  Downloading https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Building wheels for collected packages: future
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/8b/99/a0/81daf51dcd359a9377b110a8a886b3895921802d2fc1b2397e
Successfully built future
Installing collected packages: future, decorator, ratelim, geocoder
Successfully installed decorator-4.4.2 future-0.18.2 geocoder-1.38.1 ratelim-0.1.6
python3-geocoder is required
Installing python3-geocoder...
E: Unable to locate package python3-geocoder
Apt failed to install python3-geocoder!
Falling back on pypi...
Collecting geocoder
  Using cached https://files.pythonhosted.org/packages/4f/6b/13166c909ad2f2d76b929a4227c952630ebaf0d729f6317eb09cbceccbab/geocoder-1.38.1-py2.py3-none-any.whl
Requirement already satisfied: click in /usr/lib/python3/dist-packages (from geocoder)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from geocoder)
Collecting future (from geocoder)
  Downloading https://www.piwheels.org/simple/future/future-0.18.2-py3-none-any.whl (491kB)
    100% |████████████████████████████████| 491kB 148kB/s 
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from geocoder)
Collecting ratelim (from geocoder)
  Using cached https://files.pythonhosted.org/packages/f2/98/7e6d147fd16a10a5f821db6e25f192265d6ecca3d82957a4fdd592cad49c/ratelim-0.1.6-py2.py3-none-any.whl
Collecting decorator (from ratelim->geocoder)
  Using cached https://files.pythonhosted.org/packages/ed/1b/72a1821152d07cf1d8b6fce298aeb06a7eb90f4d6d41acec9861e7cc6df0/decorator-4.4.2-py2.py3-none-any.whl
Installing collected packages: future, decorator, ratelim, geocoder
Successfully installed decorator-4.4.2 future-0.18.2 geocoder-1.38.1 ratelim-0.1.6
python-beautifulsoup4 is required
Installing python-beautifulsoup4...
E: Unable to locate package python-beautifulsoup4
Apt failed to install python-beautifulsoup4!
Falling back on pypi...
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages
python3-beautifulsoup4 is required
Installing python3-beautifulsoup4...
E: Unable to locate package python3-beautifulsoup4
Apt failed to install python3-beautifulsoup4!
Falling back on pypi...
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages
python-qrcode is required
Installing python-qrcode...
python3-qrcode is required
Installing python3-qrcode...
python-icalendar is required
Installing python-icalendar...
python3-icalendar is required
Installing python3-icalendar...
python-fonts is required
Installing python-fonts...
E: Unable to locate package python-fonts
Apt failed to install python-fonts!
Falling back on pypi...
Collecting fonts
  Downloading https://files.pythonhosted.org/packages/1a/09/d3d1ab62e91b5b0167e155779120b4127d5fb622da2ffcd9bd418d21198f/fonts-0.0.3-py2-none-any.whl
Installing collected packages: fonts
Successfully installed fonts-0.0.3
python3-fonts is required
Installing python3-fonts...
E: Unable to locate package python3-fonts
Apt failed to install python3-fonts!
Falling back on pypi...
Collecting fonts
  Downloading https://files.pythonhosted.org/packages/3e/6a/ff04b5b3d22389aa57d09989ea708b93ca8f09ff57828d1ffb12ae6424a6/fonts-0.0.3-py3-none-any.whl
Installing collected packages: fonts
Successfully installed fonts-0.0.3
python-font_hanken_grotesk is required
Installing python-font_hanken_grotesk...
E: Unable to locate package python-font_hanken_grotesk
Apt failed to install python-font_hanken_grotesk!
Falling back on pypi...
Collecting font_hanken_grotesk
  Downloading https://files.pythonhosted.org/packages/f1/8f/4529f17d8578d900cea54538b0e1020473203ac62cb4fafcd76f03342370/font_hanken_grotesk-0.0.2-py2-none-any.whl (391kB)
    100% |████████████████████████████████| 399kB 186kB/s 
Installing collected packages: font-hanken-grotesk
Successfully installed font-hanken-grotesk-0.0.2
python3-font_hanken_grotesk is required
Installing python3-font_hanken_grotesk...
E: Unable to locate package python3-font_hanken_grotesk
Apt failed to install python3-font_hanken_grotesk!
Falling back on pypi...
Collecting font_hanken_grotesk
  Downloading https://files.pythonhosted.org/packages/fb/a5/2d62a85490b89381327dbfe4ece48fe9b7bda44ce564ec00d98e571d4891/font_hanken_grotesk-0.0.2-py3-none-any.whl (391kB)
    100% |████████████████████████████████| 399kB 187kB/s 
Installing collected packages: font-hanken-grotesk
Successfully installed font-hanken-grotesk-0.0.2
python-font_intuitive is required
Installing python-font_intuitive...
E: Unable to locate package python-font_intuitive
Apt failed to install python-font_intuitive!
Falling back on pypi...
Collecting font_intuitive
  Downloading https://files.pythonhosted.org/packages/a2/d8/6ad3c8727e8f1c91da474efb419c411ea88cd7f32ecc1a19612b14773b7f/font_intuitive-0.0.4-py2-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 445kB/s 
Installing collected packages: font-intuitive
Successfully installed font-intuitive-0.0.4
python3-font_intuitive is required
Installing python3-font_intuitive...
E: Unable to locate package python3-font_intuitive
Apt failed to install python3-font_intuitive!
Falling back on pypi...
Collecting font_intuitive
  Downloading https://files.pythonhosted.org/packages/cb/2b/e1327922695f8800e91c0917fa9f4c14ee9737dff974f127fde8341d68e6/font_intuitive-0.0.4-py3-none-any.whl
Installing collected packages: font-intuitive
Successfully installed font-intuitive-0.0.4
python-font_fredoka_one is required
Installing python-font_fredoka_one...
E: Unable to locate package python-font_fredoka_one
Apt failed to install python-font_fredoka_one!
Falling back on pypi...
Collecting font_fredoka_one
  Downloading https://files.pythonhosted.org/packages/8a/57/08daf462fa61641a26c9ff3c1cd0b23b3b79ddeb319b871de335b48775b4/font_fredoka_one-0.0.4-py2-none-any.whl
Installing collected packages: font-fredoka-one
Successfully installed font-fredoka-one-0.0.4
python3-font_fredoka_one is required
Installing python3-font_fredoka_one...
E: Unable to locate package python3-font_fredoka_one
Apt failed to install python3-font_fredoka_one!
Falling back on pypi...
Collecting font_fredoka_one
  Downloading https://files.pythonhosted.org/packages/44/eb/3b8e4e23afab4da77eb4744b36db9d11d9a4e85398314483006cb53fb1bf/font_fredoka_one-0.0.4-py3-none-any.whl
Installing collected packages: font-fredoka-one
Successfully installed font-fredoka-one-0.0.4
python-font_source_serif_pro is required
Installing python-font_source_serif_pro...
E: Unable to locate package python-font_source_serif_pro
Apt failed to install python-font_source_serif_pro!
Falling back on pypi...
Collecting font_source_serif_pro
  Downloading https://files.pythonhosted.org/packages/b7/6a/6abb168e0e754989979ba142962789c6a821172167406907f680cdd47824/font_source_serif_pro-0.0.1-py2-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 41kB/s 
Installing collected packages: font-source-serif-pro
Successfully installed font-source-serif-pro-0.0.1
python3-font_source_serif_pro is required
Installing python3-font_source_serif_pro...
E: Unable to locate package python3-font_source_serif_pro
Apt failed to install python3-font_source_serif_pro!
Falling back on pypi...
Collecting font_source_serif_pro
  Downloading https://files.pythonhosted.org/packages/5d/06/bbb42742135b3fc99cf330dfcc47701d46967aae602f29f4b52b5967a912/font_source_serif_pro-0.0.1-py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 47kB/s 
Installing collected packages: font-source-serif-pro
Successfully installed font-source-serif-pro-0.0.1
python-font_source_sans_pro is required
Installing python-font_source_sans_pro...
E: Unable to locate package python-font_source_sans_pro
Apt failed to install python-font_source_sans_pro!
Falling back on pypi...
Collecting font_source_sans_pro
  Downloading https://files.pythonhosted.org/packages/02/ef/f3d2e4efe40cdb153802a97c7a95b213703a5a7ec3d514459095d3cda251/font_source_sans_pro-0.0.1-py2-none-any.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 37kB/s 
Installing collected packages: font-source-sans-pro
Successfully installed font-source-sans-pro-0.0.1
python3-font_source_sans_pro is required
Installing python3-font_source_sans_pro...
E: Unable to locate package python3-font_source_sans_pro
Apt failed to install python3-font_source_sans_pro!
Falling back on pypi...
Collecting font_source_sans_pro
  Downloading https://files.pythonhosted.org/packages/4c/95/3d29d2f821bd368f74ab5fe5e7d5bf0a55a0a26d3202a56526f475e51c1b/font_source_sans_pro-0.0.1-py3-none-any.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 40kB/s 
Installing collected packages: font-source-sans-pro
Successfully installed font-source-sans-pro-0.0.1
python-wikiquotes is required
Installing python-wikiquotes...
E: Unable to locate package python-wikiquotes
Apt failed to install python-wikiquotes!
Falling back on pypi...
Collecting wikiquotes
  Downloading https://files.pythonhosted.org/packages/e6/45/0ed50f224a4559fcaea28b851b6b896cb5a0f5c8a5c382034f82e92a664d/wikiquotes-1.4.tar.gz
Collecting bs4 (from wikiquotes)
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Requirement already satisfied: lxml in /usr/lib/python2.7/dist-packages (from wikiquotes)
Requirement already satisfied: requests in /usr/lib/python2.7/dist-packages (from wikiquotes)
Collecting slacker (from wikiquotes)
  Downloading https://files.pythonhosted.org/packages/ce/e5/ea90f49e6d0905dcb2d0ab47e068b8f28f87dd97bd2e599164c693a52691/slacker-0.14.0.tar.gz
Collecting unidecode (from wikiquotes)
  Downloading https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-py2.py3-none-any.whl (238kB)
    100% |████████████████████████████████| 245kB 269kB/s 
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/dist-packages (from bs4->wikiquotes)
Building wheels for collected packages: wikiquotes, bs4, slacker
  Running setup.py bdist_wheel for wikiquotes ... done
  Stored in directory: /root/.cache/pip/wheels/0e/70/6f/0622d0ecbfee175c7f76dd337e91032a1e303ca1af6dccc85e
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /root/.cache/pip/wheels/a0/b0/b2/4f80b9456b87abedbc0bf2d52235414c3467d8889be38dd472
  Running setup.py bdist_wheel for slacker ... done
  Stored in directory: /root/.cache/pip/wheels/7e/ed/ff/f60455391d9ee3bb371ba41f1eb7eac0008e93cd3c6677a690
Successfully built wikiquotes bs4 slacker
Installing collected packages: bs4, slacker, unidecode, wikiquotes
Successfully installed bs4-0.0.1 slacker-0.14.0 unidecode-1.1.1 wikiquotes-1.4
python3-wikiquotes is required
Installing python3-wikiquotes...
E: Unable to locate package python3-wikiquotes
Apt failed to install python3-wikiquotes!
Falling back on pypi...
Collecting wikiquotes
  Downloading https://www.piwheels.org/simple/wikiquotes/wikiquotes-1.4-py3-none-any.whl
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from wikiquotes)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from wikiquotes)
Collecting slacker (from wikiquotes)
  Downloading https://www.piwheels.org/simple/slacker/slacker-0.14.0-py3-none-any.whl
Collecting bs4 (from wikiquotes)
  Using cached https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting unidecode (from wikiquotes)
  Using cached https://files.pythonhosted.org/packages/d0/42/d9edfed04228bacea2d824904cae367ee9efd05e6cce7ceaaedd0b0ad964/Unidecode-1.1.1-py2.py3-none-any.whl
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->wikiquotes)
Building wheels for collected packages: bs4
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /root/.cache/pip/wheels/a0/b0/b2/4f80b9456b87abedbc0bf2d52235414c3467d8889be38dd472
Successfully built bs4
Installing collected packages: slacker, bs4, unidecode, wikiquotes
Successfully installed bs4-0.0.1 slacker-0.14.0 unidecode-1.1.1 wikiquotes-1.4

Downloading examples and documentation...
Resources for your Inky pHAT & wHAT were copied to
/home/pi/Pimoroni/inky

Finalising Install...


Some packages could not be installed, review the output for details!
```
Then try to run the examples:
```
pi@raspberrypi:~/Pimoroni/inky/examples $ ./name-badge.py --colour yellow --type phat --name "test"
Inky pHAT/wHAT: Hello... my name is:

Use Inky pHAT/wHAT as a personalised name badge!

Traceback (most recent call last):
  File "./name-badge.py", line 29, in <module>
    inky_display = InkyPHAT(colour)
  File "/usr/local/lib/python2.7/dist-packages/inky/phat.py", line 27, in __init__
    v_flip=False)
  File "/usr/local/lib/python2.7/dist-packages/inky/inky.py", line 74, in __init__
    self.eeprom = eeprom.read_eeprom()
  File "/usr/local/lib/python2.7/dist-packages/inky/eeprom.py", line 103, in read_eeprom
    i2c = SMBus(1)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 279, in __init__
    self.open(bus)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 308, in open
    self.fd = os.open(filepath, os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/dev/i2c-1'
```
now Reboot
```
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Aug 12 11:54:02 2020 from 192.168.5.103
pi@raspberrypi:~ $ cd Pimoroni/inky/examples/
pi@raspberrypi:~/Pimoroni/inky/examples $ ./name-badge.py --colour yellow --type phat --name "test"
Inky pHAT/wHAT: Hello... my name is:

Use Inky pHAT/wHAT as a personalised name badge!


pi@raspberrypi:~/Pimoroni/inky/examples $ 
```

And display remains stubbornly unchanged.

**Comment by Gadgetoid** [comment] 2020-08-12 13:09
This is *very* likely because you had a new SSD1608-based Inky display and the changes to support these were neither merged nor released- meaning you were running drivers with no idea how to run your shiny new display.

I've rectified this so you should be able to update with:

```
sudo pip install inky --upgrade
sudo pip3 install inky --upgrade
```

Hopefully this will get you up and running. I'm really sorry for all the hassle this caused!

Note: The newer displays have a higher resolution screen and I still haven't ported all the examples over to them.

**Comment by cscashby** [comment] 2020-08-12 13:11
Great stuff - thanks! Am updating now, though the numpy dependency takes a world of time to install on the Pi Zero W - watch this space ;)

**Comment by Gadgetoid** [comment] 2020-08-12 13:16
You might be able to use `sudo apt install python-numpy python3-numpy` to avoid that *long* install. Though I thought numpy had a piwheels package to fix that!

(Ah it's not available for python 2.x - https://www.piwheels.org/project/numpy/)

**Comment by Gadgetoid** [comment] 2020-08-12 13:23
In fact you should use:

```
sudo pip install inky[rpi-gpio-output] --upgrade
sudo pip3 install inky[rpi-gpio-output] --upgrade
```

Because Inky has a non RPi simulator mode now that doesn't require SPI, I2C or GPIO.

I'd better fix that in the one-line installer... somehow!

**Comment by cscashby** [comment] 2020-08-12 15:01
Finally upgraded! --type phat gives the exactly same result; no change on the inky.

I tried --type what (don't think that's right for this) and it complained about resolution
'ValueError: Supplied width/height do not match Inky: 212x104'

So it seems no cigar :(

Is there anything I can do to poke at the electronics / see if the right signals are being presented, etc?

**Comment by Gadgetoid** [comment] 2020-08-12 15:03
You can grab the examples I've recently updated and run them without `--type` since it should auto-detect.

Just:

```
python logo.py
```

Might be that you have old examples!

**Comment by Gadgetoid** [comment] 2020-08-12 15:07
"phat" is the old 212x104 pixel Inky pHAT display, whereas I strongly suspect yours is the new 250x122 pixel Inky pHAT that's named "phatssd1608" in these examples- but just letting auto-detect do its thing is easier than dealing with this byzantine maze of different versions, sizes, colours, etc.

**Comment by cscashby** [comment] 2020-08-12 15:10
Well that was obvious. Sorry I didn't even think. Great stuff. Happy pi geek here!

![PXL_20200812_150858822.jpg](https://user-images.githubusercontent.com/1113694/90032499-57989f00-dcb6-11ea-9c14-37472aecfabe.jpg)

**Closed** 2020-08-12 15:12 UTC

**Comment by Gadgetoid** [comment] 2020-08-12 15:14
HOOOOOOOORAAAAAAAAAAAAAAAAAY!

Hopefully we'll get some time to whip up some new examples that make use of that ever-so-slightly-higher-resolution display. Oh for a @sandyjmacdonald 😆

**Comment by ljufa** [comment] 2020-08-12 20:20
worked for me as well. just make sure to use `-t "auto"` while running examples.

**Comment by glassworksSean** [comment] 2020-08-16 07:12
Hello,
I was having this same issue and my case fits all the symptoms. Assuming that I have one of these newer panels, what would be the basic process from a fresh raspberry pi install? I have tried the steps that are scattered throughout this thread, but I believe I am in a bad state on my pi and the examples don't run.

**Comment by cscashby** [comment] 2020-08-16 07:47
@Gadgetoid 's instructions above worked for me. Note you need to force raspi GPIO mode:
```
sudo pip install inky[rpi-gpio-output] --upgrade
sudo pip3 install inky[rpi-gpio-output] --upgrade
```

**Comment by Gadgetoid** [comment] 2020-08-17 11:15
I'm having second thoughts about `rpi-gpio-output` requirements being a soft dependency- but being able to simulate Inky on the desktop is kinda cool.

@glassworksSean - the one-line-installer *should* work from scratch: `curl -sSL https://get.pimoroni.com/inky | bash`

The examples and library must be in sync for everything to work properly, our one-line-installers usually handle that.

**Comment by sakumoil** [comment] 2021-06-14 10:33
I am having similar kind of problems also. Tried running the `name-badge.py` example:
```python
~/Pimoroni/inky/examples $ python name-badge.py -n"test"
Inky pHAT/wHAT: Hello... my name is:

Use Inky pHAT/wHAT as a personalised name badge!

Detected Black pHAT (SSD1608)
```
but the screen does not update. 
`inky` is at version `1.2.0`. I have enabled SPI over at `raspi-config`.

**Comment by Gadgetoid** [comment] 2021-06-14 10:56
@sakumoil anything else running on your Pi that could be tying up the SPI pins? Since it's write-only it doesn't give any useful error messages when writing just isn't happening at all.

**Comment by sakumoil** [comment] 2021-06-14 10:57
Nothing running on my Pi, it is also a fresh install I am using.

**Comment by sakumoil** [comment] 2021-06-15 11:24
It seems like that my errors were caused by the fact that the inky phat was not correctly seated. I really needed to jam the device into the pins to ensure proper seating.

**Comment by Gadgetoid** [comment] 2021-06-15 11:25
> It seems like that my errors were caused by the fact that the inky phat was not correctly seated. I really needed to jam the device into the pins to ensure proper seating.

This was going to be my next question! It's surprising how much force it needs, and easy to forget once you've been jamming boards on for years.

**Comment by awdebruijn** [comment] 2024-02-24 11:05
Hello,

I'm having the same issues as above. I have the same setup: Pi Zero WH, with a yellow InkyPhat. Installed without any issues, display is properly seated on the pins.
Strange thing is, the display is being auto detected, I can print the colour and resolution. But when I try to show anything on the display, nothing happens... I'm a bit reluctant to disconnect and reseat the ribbon cable because I fear to damage it.

Any ideas what I do wrong or how I can solve this?

**Comment by awdebruijn** [comment] 2024-02-25 20:20
Hi, thanks for the swift response :-)
When I run:
```
from inky.auto import auto
display = auto(verbose = True)
```

The output is:
`Detected Yellow pHAT (SSD1608)`

Is this what you mean?

**Comment by awdebruijn** [comment] 2024-02-26 18:54
@Gadgetoid: I used the Inky on a raspberry with poorly soldered connections before. Right now I have a new pi with pre soldered pins. Is it possible to damage it by doing so?

**Comment by Gadgetoid** [comment] 2024-02-27 09:23
> Is it possible to damage it by doing so?

It's certainly possible, but not very likely. If 5V gets bridged to anything important you'd probably know about it, and Inky's pins are well clear of the 5V supply anyway.

Which examples are you running to try and get the display working?

What version of Raspberry Pi OS?  (`lsb_release -a` and `uname -a` on command-line)

It might also be worth trying the work-in-progress updated code, but only as a last ditch effort since there's probably a simpler answer - https://github.com/pimoroni/inky/pull/182

**Comment by awdebruijn** [comment] 2024-02-28 18:05
I cloned the Inky repo and tried all the examples, no errors, but nothing happens on the screen. 
I'm running Raspberry Pi OS: Raspbian GNU/Linux 11 (bullseye).
The identify.py script outputs a 212x104 yellow, PCB variant 1.2 display variant 12.

**Comment by awdebruijn** [comment] 2024-03-02 09:50
@Gadgetoid: You're probably super busy, but if you don't mind, I want to get to the bottom of this. I bought everything brand new and I can't return it anymore. I would just like to enjoy building cool stuff for this display.
If you could please give me some guidance or another place where I should as for help, I would highly appreciate.

**Comment by gingertastrophe** [comment] 2024-05-22 01:45
I'm having the same issue too with my SSD1608 Red pHAT. It was working fine and the screen refreshed without issues on my Raspberry Pi Zero 2 W, but I had to swap that one out with a new Zero 1 W. I resoldered the pins and now my inky won't update on either of the devices, despite it being detected without issues.
